### ISSUE TITLE
request: would like to have crop data output

### ISSUE THREAD

**Issue by manassm** [liusida/ComfyUI-AutoCropFaces#1]
I really like how well this node works. I think it works better for my use than WAS image crop face node.
I wish it had crop data output as well, so I can zoom into a face, use it for i2i, and paste it back onto the original image.
It might be even better if you can make separate crop paste node as well, but if WAS image paste face node is compatible with the paste data output, that may be suffice as well. 

Thank you very much.

**Comment by liusida** [comment]
Thanks @manassm 

> I wish it had crop data output as well, so I can zoom into a face, use it for i2i, and paste it back onto the original image.

Can you explain this a bit more, maybe give a visual example of your use case (workflow)? I am having trouble understand the feature you described.

Is crop data output two coordinates? x1, y1, x2, y2?

**Comment by liusida** [comment]
I've installed WAS (https://github.com/WASasquatch/was-node-suite-comfyui) for the first time, and I see what CROP_DATA was.

Sorry, never installed that and didn't know there's another node for this purpose, xD

**Comment by liusida** [comment]
![image](https://github.com/liusida/ComfyUI-AutoCropFaces/assets/14249458/1a53ee4c-0d2b-4825-beb9-15190b9f8379)

**Comment by liusida** [comment]
As you mentioned, I am thinking about, maybe later, I'll make a similar node to "Image Paste Crop" from WAS suite, since that suite is a bit heavy and has too many dependencies.

**Comment by manassm** [comment]
![스크린샷 2024-05-20 161407](https://github.com/liusida/ComfyUI-AutoCropFaces/assets/70854401/1c61b569-cd98-431d-b013-be58f0d507b2)
This is the example workflow I am working on, where I take face part of the image, crop it out, modify it, and paste it back to the original image. Here I am using the WAS node version of it, but I personally find your node to work better, in some cases, for face detection and cropping the portion with only the face. 
Thank you for your support.

**Comment by liusida** [comment]
Cropping is for rectangle areas. Do you mean you want to do face swapping? There's a node for that, I think.

**Comment by liusida** [comment]
Try this one: https://github.com/Gourieff/comfyui-reactor-node

**Comment by manassm** [comment]
I'm not sure about particular one you mentioned yet, but seemed like face swapping didn't particularly work well with stylied anime faces. But I will look into it. Thank you.

**Comment by liusida** [comment]
> I'm not sure about particular one you mentioned yet, but seemed like face swapping didn't particularly work well with stylied anime faces. But I will look into it. Thank you.

Yeah, you're right. I think nobody has really thought about swapping faces for anime characters yet.

**Comment by liusida** [comment]
![face](https://github.com/liusida/ComfyUI-AutoCropFaces/assets/14249458/2be22533-e9bb-48ed-a985-3e7ad8060fde)

I think you'll be like this @manassm 

workflow embedded in the png
