### ISSUE TITLE
How can I make a cropped face cover a larger area?

### ISSUE THREAD

**Issue by bigcat88** [liusida/ComfyUI-AutoCropFaces#11]
Testing the node on different photographs, and on most of them, even with different aspect rates, the result is almost always cut off by one of the following:

1. Ears
2. Hair
3. Chin

Is it possible to add some kind of parameter that will say to capture not only the center of the face, but a little more pixels around?

*I tried changing the scale_factor, but for some reason it doesn’t affect the result in any way..*

This would be very useful for ComfyUI workflows.

**Comment by liusida** [comment]
"I tried changing the scale_factor, but for some reason it doesn’t affect the result in any way.."

That should be a bug. Let me check real quick!!

**Comment by liusida** [comment]
Fixed. Please give it another try. Thanks!

P.S. I was dreamwalking these days. Ha-ha. Sorry about that.

**Comment by bigcat88** [comment]
from fast checking: looks like now it is working.
 
 Thank you for fast reaction.
