### ISSUE TITLE
By passing the Index out of range error message ?

### ISSUE THREAD

**Issue by Crazy-Lion-QC** [liusida/ComfyUI-AutoCropFaces#4]
The title says it all.
Would it be possible to add a bypass for the error message/workflow-crash when a face is simply not found ?
Thank you.

**Comment by liusida** [comment]
What does this message look like? Please paste the message here for me to reproduce.

I think it doesn't raise any error by default. By default, if no face is found, just return the original image.

![image](https://github.com/liusida/ComfyUI-AutoCropFaces/assets/14249458/ed178cd3-d04a-4231-a9c0-01924b83e376)
